apiVersion: v1
kind: Pod
metadata: 
  name: nginx-example
spec: 
  containers: 
    - name: nginx
      image: nginx
      resources:
        limits:
          memory: 10Mi
        requests:
          memory: 5Mi
