apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: myapp-replicaset
  labels: 
    app: myapp
spec:
  selector:
    matchLabels:
      env: dev
  replicas: 3
  template:
    metadata: 
      name: nginx-example
      labels:
        env: dev
    spec: 
      containers: 
        - name: nginx
          image: nginx
