apiVersion: v1
kind: Pod
metaData:
  name: httpGetExample
spec:
  containers:
    - name: nginx
      image: nginx
      ports:
        - containerPort: 8080
      livenessProbe:
        tcpSocket:
          port: 3306
