apiVersion: v1
kind: Pod
metadata: 
  name: nginx-example
  labels:
    env: dev
spec: 
  containers: 
    - name: nginx
      image: nginx
      env:
        - name: KEY_ONE
          value: "Value one"
      securityContext:
        runAsUser: 0  
        capabilities:
          add: ["MAC_ADMIN", "SYS_TIME"]
